### ISSUE TITLE
Setup Steps Unclear

### ISSUE THREAD

**Issue by Craig-Macomber** [mlo31415/FancyDownloader#1]
I'm hoping to use this tool (thanks for writing it!) as a mitigation for wikidot's backup tool bring broken, but I'm struggling a bit with the setup.

I'm pretty out of date when it comes to python development, so maybe I did something real silly here.

So far I made a venv and pip installed `pywikibot` and `mwparserfromhell`.

Questions:

1. Its unclear to me what logging package you are using (what do I need to install to make your `from Log import Log, LogOpen` work. Is there some specific package I should install?
2. Is there something I need to install to get the "HelpersPackage" as well?
3. Comment at the top mentions `url.txt` for config and credentials, but it looks like `user-config.py` has that information instead. Do I need both? Also looks like `user-config.py` expects a `user-password.py` which I need to create. Is there a particular variable I should assign to the password in there?

**Comment by mlo31415** [comment]
Craig --

> -----Original Message-----
> From: Craig ***@***.***>
> Sent: Saturday, February 19, 2022 12:49 AM
> To: mlo31415/FancyDownloader ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: [mlo31415/FancyDownloader] Setup Steps Unclear (Issue #1)
> 
> I'm hoping to use this tool (thanks for writing it!) as a mitigation for wikidot's
> backup tool bring broken, but I'm struggling a bit with the setup.
> 
> I'm pretty out of date when it comes to python development, so maybe I did
> something real silly here.
> 
> So far I made a venv and pip installed pywikibot and mwparserfromhell.

Question back: Are you running on Wikidot or Mediawiki?  Fancyclopedia was on Wikidot for nearly a decade before giving up on it and moving to an Mediawiki instance.

FancyDownloader started on Wikidot and then got re-written for Mediawiki.  The first MediaWiki checkin was January 7, 2020, so if you're still on Wikidot, you want to get the last 2019 version.

Assuming you want Mediawiki (which I suspect is wrong, but I remember some of the details for it), I'll answer below.  If you really want Wikidot, I'll be glad to help you, but I'll have to figure out my old code along with you!

-- mlo

> Questions:
> 
> 1.	Its unclear to me what logging package you are using (what do I need
> to install to make your from Log import Log, LogOpen work. Is there some
> specific package I should install?
> 2.	Is there something I need to install to get the "HelpersPackage" as
> well?

Log.py and HelpersPackage.py are both part of the mlo31415/HelpersPage repository, so download them from there.

> 3.	Comment at the top mentions url.txt for config and credentials, but
> it looks like user-config.py has that information instead. Do I need both?
> Also looks like user-config.py expects a user-password.py which I need to
> create. Is there a particular variable I should assign to the password in there?

If you dig around in the pywikibot docs this *is* explained, but not very clearly and I will admit to not remembering the details at this point...

Your user-config.py will look something like this:
==============================================
mylang = 'fancyclopedia'#'en'
#langs={'en' : 'fancyclopedia.org'}
family = 'fancyclopedia'
# usernames['fancyclopedia']['mlo'] = u'ExampleBot'
family_files['fancyclopedia'] = 'https://fancyclopedia.org/api.php'
usernames['fancyclopedia']['fancyclopedia'] = 'mlo'
password_file = "user-password.py"
==============================================
I do not pretend that those are optimal settings as I got to them through some trial and error!  But they do work for me.  Note that the password_file parameter specifies "user-password.py" as the source of the password.  At this point I don't recall the details of how I created it since it's been a couple years.  But, here it is:
==============================================
# This is an automatically generated file used to store
# BotPasswords.
#
# As a simpler (but less secure) alternative to OAuth, MediaWiki allows bot
# users to uses BotPasswords to limit the permissions given to a bot.
# When using BotPasswords, each instance gets keys. This combination can only
# access the API, not the normal web interface.
#
# See https://www.mediawiki.org/wiki/Manual:Pywikibot/BotPasswords for more
# information.
# JRB
('mlo', BotPassword('mlosbot', 'xxxxxxxxxxxxxxxxxxxxxxxxxx'))
==============================================

You'll need to put your own password in as well as changing the user ID.

**Comment by Craig-Macomber** [comment]
Thanks for the response! That helps clarify things.

I'm looking to download wikidot wikis (their backup service died, and the whole system seems to be slowly dying), and I want an offline copy to avoid data-loss if wikidot goes down. Some context is over at https://wiki.archiveteam.org/index.php/Wikidot .

Anyway, your down loader (which is linked from there) looks a little simpler than their setup so I figured I'd start here.

I'll fork the 2019 version and see if I can make that work. I'll let you know if I need further help. If I can get it working I'll make a readme so others stuck on wikidot can more easily benefit from your work.

**Comment by Craig-Macomber** [comment]
I got it at least partly working here: https://github.com/Craig-Macomber/FancyDownloader/tree/wikidot

I still have a bit of further work to do to get everything I want (A bit easier configuration for multiple sites, and fixing large file downloads), but I don't think I need any further help at this point. Pointing me to the correct revision for wikidot support was the main thing I needed!
